name: neuron
channels:
  - conda-forge
  - defaults
dependencies:
  - _pytorch_select=0.1
  - blas=2.116
  - blas-devel=3.9.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - colorama=0.4.6
  - freetype=2.12.1
  - jpeg=9e
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.4
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libtiff=4.5.0
  - libwebp-base=1.3.0
  - libzlib=1.2.13
  - llvm-openmp=16.0.4
  - lz4-c=1.9.4
  - mpi=1.0
  - mpich=4.1.1
  - ncurses=6.3
  - ninja=1.11.1
  - numexpr=2.8.4
  - numpy-base=1.24.3
  - openblas=0.3.21
  - openssl=3.1.0
  - opt_einsum=3.3.0
  - pandas=2.0.1
  - pandoc=3.1.2
  - pip=23.1.2
  - pycparser=2.21
  - pyro-api=0.1.2
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - readline=8.2
  - setuptools=67.7.2
  - six=1.16.0
  - sqlite=3.42.0
  - tbb=2021.9.0
  - tk=8.6.12
  - typing-extensions
  - typing_extensions
  - tzdata=2023c
  - wheel=0.40.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.0.8
      - attrs==22.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.1
      - bleach==5.0.1
      - cffi==1.15.1
      - colorednoise==2.1.0
      - cycler==0.11.0
      - datetime==4.5
      - debugpy==1.6.3
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - executing==1.0.0
      - fastjsonschema==2.16.1
      - filelock==3.12.0
      - fonttools==4.37.1
      - hmmlearn==0.3.0
      - importlib-metadata==4.12.0
      - ipykernel==6.15.2
      - ipython==8.5.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.2
      - jedi==0.18.1
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.16.0
      - jupyter==1.0.0
      - jupyter-client==7.3.5
      - jupyter-console==6.4.4
      - jupyter-core==4.11.1
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.3
      - kaleido==0.2.1
      - kiwisolver==1.4.4
      - lxml==4.9.1
      - markupsafe==2.1.1
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mistune==2.0.4
      - mpmath==1.3.0
      - nbclient==0.6.8
      - nbconvert==7.0.0
      - nbformat==5.4.0
      - nest-asyncio==1.5.5
      - networkx==3.1
      - neuron==8.2.1
      - notebook==6.4.12
      - numba==0.57.1
      - numpy==1.23.3
      - packaging==21.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.2.0
      - plotly==5.10.0
      - prometheus-client==0.14.1
      - prompt-toolkit==3.0.31
      - psutil==5.9.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.13.0
      - pyparsing==3.0.9
      - pyro-ppl==1.8.4
      - pyrsistent==0.18.1
      - pytz==2022.2.1
      - pyzmq==23.2.1
      - qtconsole==5.3.2
      - qtpy==2.2.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - send2trash==1.8.0
      - soupsieve==2.3.2.post1
      - stack-data==0.5.0
      - sympy==1.12
      - tenacity==8.0.1
      - terminado==0.15.0
      - threadpoolctl==3.1.0
      - tinycss2==1.1.1
      - torch==2.0.1
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.3.0
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - widgetsnbextension==4.0.3
      - zipp==3.8.1
      - zope-interface==5.4.0
